export const propertyTypes = [
  "Apartment",
  "Villa",
  "Townhouse",
  "Office",
  "Retail",
  "Building",
  "Other (Residential)",
  "Other (Commercial)",
] as const;

export const propertyLocations = [
  "Al Barari",
  "Al Barsha",
  "Al Barsha South",
  "Al Furjan",
  "Al Jaddaf",
  "Al Jaddaf Waterfront",
  "Arabian Ranches 1",
  "Arabian Ranches 2",
  "Arabian Ranches 3",
  "Arjan",
  "Business Bay",
  "Cherrywoods",
  "City Walk",
  "Damac Hills 1 & 2",
  "Damac Lagoons",
  "Discovery Gardens",
  "Downtown",
  "Dubai Creek Harbour",
  "Dubai Hills Estate",
  "Dubai Silicon Oasis",
  "Emirates Hills",
  "Emaar Beachfront",
  "Emaar South & Dubai South / Expo City",
  "Falcon City",
  "Greens & Views",
  "IMPZ",
  "JLT / Uptown / The Hills",
  "Jumeirah 1, 2, 3",
  "Jumeirah Bay Island",
  "Jumeirah Golf Estates",
  "Jumeirah Islands",
  "Jumeirah Park",
  "JVT",
  "JVC",
  "Lakes",
  "Living Legends",
  "Madinat Jumeirah Living",
  "Marina & JBR",
  "Meadows",
  "Mira / Mira Oasis",
  "MBR District One",
  "Motor City",
  "Mudon",
  "Palm Jumeirah",
  "Port de la Mer",
  "Port Rashid",
  "Remraam",
  "Serena",
  "Springs",
  "Studio City",
  "Sustainable City",
] as const;

export const serviceTypes = ["rent", "sell", "appraisel"] as const;
